apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudnotes-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudnotes
  template:
    metadata:
      labels:
        app: cloudnotes
    spec:
      containers:
      - name: cloudnotes
        image: atiqbitstream/cloudnotes:afeaf87eec7bc6430462e59ebf51191043a32a3a
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 512Mi
        env:
          - name: APP_TITLE
            valueFrom:
             configMapKeyRef:
                name: cloudnotes-config
                key: APP_TITLE
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cloudnotes-secret
                key: DB_PASSWORD
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 20